// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdzckpvemvekojzsuufw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkemNrcHZlbXZla29qenN1dWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTM3NzEsImV4cCI6MjA3MjkyOTc3MX0.IAAh7-lIbRYBlO6gXXMlMpn9yEcM1vGSQfdqJqI7FXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});